### ISSUE TITLE
Installing raises Error: Your .elm/packages/ directory may be corrupted.

### ISSUE THREAD

**Issue by cuducos** [sanichi/elm-md5#1]
I can't install it here. I'm using Elm 0.17.1 — but people from Slack had the same issue with Elm 0.18.

```console
$ cat elm-package.json
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/user/project.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "4.0.5 <= v < 5.0.0",
        "elm-lang/html": "1.1.0 <= v < 2.0.0",
        "evancz/elm-http": "3.0.1 <= v < 4.0.0"
    },
    "elm-version": "0.17.1 <= v < 0.18.0"
}

$ elm-package install sanichi/elm-md5 1.0.0
To install sanichi/elm-md5 I would like to add the following
dependency to elm-package.json:

    "sanichi/elm-md5": "1.0.0 <= v < 2.0.0"

May I add that to elm-package.json for you? [Y/n] y

Error: Your .elm/packages/ directory may be corrupted. I was led to beleive that
sanichi/elm-md5 existed, but I could not find anything when I went to look up
the published versions of this package.
```

**Comment by sanichi** [comment]
Right now, I don't know what the problem is for Elm 0.17.1. Even setting the version range to `1.0.0 <= v < 1.0.1` before you try to install it (as instructed in the README.md) doesn't fix it.

As a workaround, for now, you could just grab the [0.17.1 version of the only file you need](https://github.com/sanichi/elm-md5/blob/1.0.0/src/MD5.elm) and add it to your project files. If you do this and it works, please let me know.

There doesn't appear to any problems with the Elm 0.18 version.

**Comment by cuducos** [comment]
Sure thing. It worked in 0.18. 
Let;s wait and see ; )
Many thanks for the quick reply.
